api:
  zusatzdatenserver:
    url: https://ppc-dev.dc.man.lan/api/
  productioncalendar:
    url: https://ppc-dev.dc.man.lan/productioncalendar/
  core:
    url: http://dcdefrdlx045vi.dc.man.lan:5603/